name: Docker Image CI Build

on:
    push:
        branches:
            - main

jobs:
    buildImage:
        runs-on: ubuntu-latest
        env:
            REPOSITORY: ghcr.io/marjamis/config-image-puller

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub
              uses: docker/login-action@v2
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push to Github Package Registry
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: |
                      ${{ REPOSITORY }}:latest
                      ${{ REPOSITORY }}:$(date +%s)
