name: Docker Image CI Build

on:
    push:
        branches:
            - main

jobs:
    buildImage:
        runs-on: ubuntu-latest

        steps:
            - name: "Sets the date value"
              id: set_date
              run: echo "::set-output name=current_date::$(date +%s)"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push to Github Package Registry
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: |
                      ghcr.io/marjamis/config-image-puller:latest
                      ghcr.io/marjamis/config-image-puller:${{ steps.set_date.outputs.current_date }}
