name: Docker Image CI

on:
    push:
        branches:
            - main

jobs:
    buildImage:
        runs-on: ubuntu-latest
        env:
            REGISTRY: docker.pkg.github.com
            REPOSITORY: docker.pkg.github.com/marjamis/config-image-puller

        steps:
            - uses: actions/checkout@master
            - name: Build the Docker image
              run: |
                  docker build . --file Dockerfile --tag $REPOSITORY:latest
                  docker tag $REPOSITORY:latest $REPOSITORY:$(date +%s)
            - name: Push image to Github Package Registry
              run: |
                  docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} $REGISTRY
                  docker push -a $REPOSITORY
